### ISSUE TITLE
Finishing a tournament then moving to battle breaks

### ISSUE THREAD

**Issue by Roshinator** [Tankken/Bugs#10]
**Describe the bug**
Finisha  tournament and adding AIs in battle fails

**To Reproduce**
1. Play a tournament though
2. Open battle mode
3. Add an AI as the first player
4. it should fail

**Expected behavior**
It should not fail

**Additional context**
Prelim testing shows that for some reason adding an AI as p1 in this context adds a number to the localplayernums list, this should not be the case and why it is happening could be a result of something not getting cleared from the controllerbinder list

**Comment by Ravbug** [comment]
Resolved in 0.0.4.
