### ISSUE TITLE
Driving over Holes

### ISSUE THREAD

**Issue by DamnNameTaken** [Tankken/Bugs#17]
I somehow managed to drive over one of the holes in Campaign Mission 2 reaching the other side.

**To Reproduce**
1, Go to the lowest Hole.
2. Keep holding S and D.
3. The Tank will start jiggling until it starts driving over it.

You can also go back using A an S, so this likely works in all directions.

**Expected behavior**
Not being able to go over the Holes.

**Screenshots / Videos**
https://medal.tv/clips/61474540/d133706BLcmo

**System Information:**
 - OS: Windows
 - Game Version [0.0.4a]

**Additional context**
It looks like the tank is gaining height while jiggling until it is ontop of the obstacle.

**Comment by Ravbug** [comment]
Good catch!
