### ISSUE TITLE
Shooting bullets through walls on level 2/ bullets getting suck in the wall on level .

### ISSUE THREAD

**Issue by skullmaster322** [Tankken/Bugs#4]
https://youtu.be/RYsYMCBT8JE video of the bug I when up to the wall straight and shot a an upper angle/lower angle and if i shot it straight it would just get stuck in the wall. Tankista-windows-v0.0.1.7z

**Comment by Ravbug** [comment]
For Level 2, you need to use right click to place a mine, however we can see that's unclear
