### ISSUE TITLE
The title becomes unresponsive when the user change the controller settings to D mode after joining as a local player with a Logitech F310 controller

### ISSUE THREAD

**Issue by Zakadius** [Tankken/Bugs#5]
**Describe the bug**
The title becomes unresponsive when a user switches between the X and D mode on the logitech F310

1. Go to 'classic campaign'.
2. Select Play Local.
3. While in X mode on the controller, press LB and RB to add a local player.
4. Switch to D mode on the back of the controller.
5. Observe that the game becomes unresponsive.

**Expected behavior**
The title remains responsive.

**Desktop:**
 - OS: [Windows 10 pro Version 19041]
 - Version [0.0.1.7]

**Comment by Roshinator** [comment]
When a device is disconnected in Add Players, it will now be removed from the list.
