### ISSUE TITLE
Error in battle with nonconsecutive teams

### ISSUE THREAD

**Issue by Ravbug** [Tankken/Bugs#9]
**Describe the bug**
When a match is won with nonconsecutive team names, an error is displayed 

**To Reproduce**
1. Start a new battle game
2. join 1 human player, and set to team 0
3. join 3 AI players, set to gray tanks, and set to team 3
4. Run the match, and allow the AI to kill you
5. See error

**Expected behavior**
The match should end correctly

**System Information:**
 - OS: macOS 10.15
 - Game Version 0.0.3 development version

**Additional context**
This version of the game is not public at time of writing

**Comment by Roshinator** [comment]
Fixed. The problem was with assuming the indices of the team dictionary keys were the same as the team numbers themselves.
